import type { NextPage } from 'next';
import Head from 'next/head';
import { useTheme } from '@mui/material/styles';
//
import RadioButton from '../component/radioButton';
//
import { useAppDispatch, useAppSelector } from '../hooks';
//

const Home: NextPage = () => {
  const theme = useTheme();

  const state = useAppSelector((state) => state.themeReducer.font);
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name='description' content='Generated by create next app' />
        <link rel='icon' href='/favicon.ico' />
      </Head>

      <main>
        <RadioButton />
        <p>
          Lorem ipsum dolor sit amet consectetur adipisicing elit. Cumque
          nostrum totam reprehenderit, aperiam optio temporibus, voluptas
          recusandae minus repellendus libero ab et dolore dolores fuga quos
          odit placeat accusantium soluta.
        </p>
      </main>

      <footer></footer>
    </div>
  );
};

export default Home;
